/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List studies (cockpit home)
         * @description Read route the cockpit uses to render the study list. Public.
         */
        get: operations["listStudies"];
        put?: never;
        /**
         * Create a study (create_study)
         * @description Opens the evidence ledger from a brief. The human supplies business judgment (objective, target, metric, constraints, budget); this returns the study id everything else hangs off.
         */
        post: operations["createStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studies/{studyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        /**
         * Full study detail / evidence ledger (study detail)
         * @description The cockpit's main read and the shape grade_study.py fetches. Returns the study plus its dataset version, hypotheses, runs, critiques, decisions, feedback, and artifacts — the whole ledger in one call. Public.
         */
        get: operations["getStudy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studies/{studyId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        /**
         * Live agent activity for a study (Server-Sent Events)
         * @description The control plane proxies the agent runtime's Managed Agents event stream through to the cockpit: agent narration, tool-use, tool-results, nudges, approval requests, and a final done event. Public, like the other reads. Each SSE `data:` line is a JSON object with a `kind` discriminator (e.g. session.created, agent.activity, tool.use, tool.result, nudge, approval.needed, study.done, loop.error). Subscribing also starts the study's session if it has not started yet.
         */
        get: operations["streamStudy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studies/{studyId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject a human "suggest changes" message into the live session
         * @description Steering for a live study. The control plane proxies the text to the agent runtime, which injects it as a user.message into the running Managed Agents session so it affects the next step (not just a ledger note). The cockpit also records the same text via /api/feedback for the evidence ledger. Returns 503 { error: "runtime_unavailable" } when no runtime is wired.
         */
        post: operations["suggestChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profile the dataset (profile_dataset)
         * @description Profiles the study's dataset and writes a dataset version: columns with dtypes and missingness, candidate leakage columns (flagged, defaulting to banned), the split strategy, and the seed.
         */
        post: operations["profileDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose hypothesis cards (propose_experiments)
         * @description Returns N hypothesis cards (statement, rationale, model family, candidate features, expected outcome). These render as the experiment cards in the cockpit; the human approves, edits, or rejects them.
         */
        post: operations["proposeExperiments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request human approval (request_approval)
         * @description Creates a pending approval the cockpit surfaces (e.g. launching N runs at an estimated cost, or unbanning a leakage feature). Compute cannot launch until a matching approval is recorded via /api/feedback (type=approval).
         */
        post: operations["requestApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch a sandboxed experiment (launch_experiment)
         * @description Verifies an approval exists, submits the experiment manifest to the Modal runner, and records a run with metrics, params, artifacts, and provenance (dataset_hash, code_hash, seed). The manifest is the only thing handed to the runner — no arbitrary code. Tuning on 'test' is rejected.
         */
        post: operations["launchExperiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query runs (query_runs)
         * @description Filter the ledger's runs by metric thresholds, model family, hypothesis, tags, or linked critique kind. Powers both the cockpit run table and the agent's "show me runs where recall improved but precision dropped" queries.
         */
        post: operations["queryRuns"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/critiques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a critique (record_critique)
         * @description Persist a methodological critique of a run — leakage, test-set tuning, metric, calibration, or robustness — with a finding, a recommendation, and the decision it led to. This is how the experiment-critic writes evidence into the ledger; the rubric's "caught an issue" and "leakage review before training" checks read it. The id is server-assigned.
         */
        post: operations["recordCritique"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a decision (record_decision)
         * @description Persist a decision — promote, reject, rerun, branch, or stop — naming the run it acted on and the reason. Every promote/reject in the loop is recorded so the ledger captures what the agent (or human) decided and why. The id is server-assigned.
         */
        post: operations["recordDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record human feedback (record_human_feedback)
         * @description Stores a human judgment and (for natural-language notes) its parsed constraints. An approval is feedback of type=approval. The ergonomic breakthrough: the human gives judgment, the agent gets a structured constraint it can apply to later manifests (applied_feedback_id).
         */
        post: operations["recordHumanFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate the model card (write_report)
         * @description Assembles the final report — objective, data, split, experiments table, best vs baseline, risks, rejected ideas, next steps, a reproducible command, and a provenance footer — stores it in R2, and records an artifact of kind=report.
         */
        post: operations["writeReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grade against the rubric (grade_study_against_rubric)
         * @description Evaluates the study against docs/rubric.json and returns pass/fail per check plus an overall verdict. This is the machine-checkable definition of done — the Stop hook calls it so "done" is verifiable without a human.
         */
        post: operations["gradeStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            detail?: string;
        };
        Budget: {
            /** @default 20 */
            max_trials: number;
            /** @default 600 */
            budget_seconds: number;
        };
        Study: {
            id: string;
            brief: string;
            owner?: string;
            /** @enum {string} */
            task_type?: "binary_classification" | "regression";
            dataset_id: string;
            target: string;
            metric: string;
            metric_rationale?: string;
            budget?: components["schemas"]["Budget"];
            /** @default docs/rubric.json */
            rubric: string;
            /**
             * @default open
             * @enum {string}
             */
            status: "open" | "done" | "stopped";
            constraints?: components["schemas"]["Constraints"];
            /** Format: date-time */
            created_at?: string;
        };
        CreateStudyRequest: {
            brief: string;
            owner?: string;
            /** @enum {string} */
            task_type?: "binary_classification" | "regression";
            dataset_id: string;
            target: string;
            metric: string;
            metric_rationale?: string;
            constraints?: components["schemas"]["Constraints"];
            budget?: components["schemas"]["Budget"];
            /** @default docs/rubric.json */
            rubric: string;
        };
        CreateStudyResponse: {
            id: string;
            /** @enum {string} */
            status?: "open";
        };
        Constraints: {
            primary_metric?: string;
            guardrails?: {
                /** @example false_positive_rate <= 0.20 */
                expr?: string;
                rationale?: string;
            }[];
            banned_columns?: string[];
            /** @default false */
            require_interpretability: boolean;
        };
        ColumnProfile: {
            name: string;
            dtype: string;
            missing_fraction?: number;
            n_unique?: number;
            /** @default false */
            is_candidate_leakage: boolean;
            leakage_reason?: string;
        };
        SplitStrategy: {
            /** @enum {string} */
            strategy: "time_based" | "stratified";
            time_col?: string;
            /** @description [train, validation, test] */
            ratios?: number[];
            seed: number;
        };
        DatasetVersion: {
            id: string;
            study_id: string;
            file_hash: string;
            row_count: number;
            columns?: components["schemas"]["ColumnProfile"][];
            target_definition?: string;
            split_strategy?: components["schemas"]["SplitStrategy"];
            leakage_candidates?: string[];
            banned_columns?: string[];
            /** @description Where the runner pulls the CSV; the agent echoes it onto launch manifests. */
            dataset_uri?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Hypothesis: {
            id: string;
            study_id: string;
            /** @description A falsifiable claim. */
            statement: string;
            rationale?: string;
            model_family?: string;
            features?: string[];
            expected_outcome?: string;
            /** @enum {string} */
            status?: "proposed" | "approved" | "rejected";
            /** Format: date-time */
            created_at?: string;
        };
        ModelSpec: {
            /** @enum {string} */
            family: "dummy" | "logistic_regression" | "linear_regression" | "random_forest" | "gradient_boosting" | "hist_gradient_boosting" | "xgboost" | "lightgbm";
            params?: {
                [key: string]: unknown;
            };
        };
        SearchSpec: {
            /** @default false */
            enabled: boolean;
            /** @default 20 */
            max_trials: number;
            /** @default 600 */
            timeout_seconds: number;
            /** @default tpe */
            sampler: string;
            /**
             * @description Tuning on 'test' is forbidden and rejected by the runner.
             * @default validation
             * @enum {string}
             */
            tune_on: "validation";
        };
        MetricSpec: {
            /**
             * @example recall_at_fpr
             * @example pr_auc
             * @example roc_auc
             * @example rmse
             * @example mae
             */
            primary: string;
            max_fpr?: number;
        };
        /** @description An experiment to run in the Modal sandbox. Two mutually exclusive modes (script XOR model): supply `script` — an agent-authored Python training program the network-isolated Modal Sandbox runs — OR `model` + `metric` for the legacy manifest→sklearn path. `study_id`, `hypothesis_id`, `dataset_uri`, `target`, `task_type`, `split`, and `features` are required in both modes. */
        ExperimentManifest: {
            study_id: string;
            hypothesis_id: string;
            /** @description Where the runner pulls the CSV (R2 key or public URL). */
            dataset_uri: string;
            target: string;
            /** @enum {string} */
            task_type: "binary_classification" | "regression";
            split: components["schemas"]["SplitStrategy"];
            /** @description MUST exclude banned/leaky columns. */
            features: string[];
            banned_columns?: string[];
            /** @description Agent-authored, self-contained Python training code. Reads the CSV at /work/data.csv, makes the deterministic split FIRST using split.seed, trains, tunes on validation only (never test), evaluates on test once, and writes /work/result.json := {metrics, params, artifacts}. Runs in a network-isolated Modal Sandbox; pandas/numpy/scikit-learn are installed. Provided INSTEAD of model/metric (script XOR model). */
            script?: string;
            /**
             * @description Where the script tunes thresholds/hyperparameters. Tuning on 'test' is forbidden and rejected. Honored on the script path (the legacy path uses search.tune_on).
             * @default validation
             * @enum {string}
             */
            tune_on: "validation";
            model?: components["schemas"]["ModelSpec"];
            search?: components["schemas"]["SearchSpec"];
            metric?: components["schemas"]["MetricSpec"];
            /** @description Human feedback id whose parsed constraint shaped this manifest. */
            applied_feedback_id?: string;
            /**
             * @example [
             *       "baseline"
             *     ]
             */
            tags?: string[];
        } & (unknown | unknown);
        Run: {
            id: string;
            study_id: string;
            hypothesis_id: string;
            manifest_id?: string;
            tracker_run_id?: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed";
            metrics?: {
                [key: string]: number;
            };
            params?: {
                [key: string]: unknown;
            };
            /** @description name -> { uri, kind } */
            artifacts?: {
                [key: string]: unknown;
            };
            /** @description What this run tests and why. */
            rationale?: string;
            tags?: string[];
            /** @constant */
            executor?: "modal-runner";
            dataset_hash?: string;
            code_hash?: string;
            seed?: number;
            /** Format: date-time */
            created_at?: string;
        };
        Critique: {
            id: string;
            study_id: string;
            target_run_id?: string;
            /** @enum {string} */
            kind: "leakage" | "test_set_tuning" | "metric" | "calibration" | "robustness";
            finding: string;
            recommendation?: string;
            /** @enum {string} */
            led_to_decision?: "promote" | "reject" | "rerun" | "branch" | "stop";
            /** Format: date-time */
            created_at?: string;
        };
        Decision: {
            id: string;
            study_id: string;
            /** @enum {string} */
            action: "promote" | "reject" | "rerun" | "branch" | "stop";
            promoted_run_id?: string;
            rejected_run_id?: string;
            reason?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Feedback: {
            id?: string;
            study_id: string;
            target_id?: string;
            /** @enum {string} */
            type: "approval" | "ban_feature" | "change_metric" | "increase_budget" | "focus_segment" | "note";
            /** @enum {string} */
            scope?: "study" | "hypothesis" | "run" | "experiment";
            content: string;
            /** @description e.g. { primary_metric: 'recall', guardrail: 'false_positive_rate <= 0.20' } */
            parsed_constraints?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        ApprovalRequest: {
            study_id: string;
            experiment_ids?: string[];
            reason: string;
            estimated_cost_seconds?: number;
        };
        Artifact: {
            id: string;
            study_id: string;
            /** @enum {string} */
            kind: "report" | "plot" | "model" | "confusion_matrix";
            uri: string;
            dataset_hash?: string;
            code_hash?: string;
            seed?: number;
            meta?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
        };
        Report: {
            study_id: string;
            /** @description R2 location of the rendered report. */
            uri: string;
            best_run_id?: string;
            baseline_run_id?: string;
            compares_best_to_baseline?: boolean;
            reproducible_command?: string;
            provenance?: {
                dataset_hash?: string;
                code_hash?: string;
                seed?: number;
            };
        };
        RunQuery: {
            study_id: string;
            model_family?: string;
            hypothesis_id?: string;
            tags?: string[];
            /** @enum {string} */
            critique_kind?: "leakage" | "test_set_tuning" | "metric" | "calibration" | "robustness";
            /** @description e.g. recall >= 0.7 AND precision < 0.5 */
            metric_filters?: {
                name: string;
                /** @enum {string} */
                op: "<" | "<=" | "=" | ">=" | ">";
                value: number;
            }[];
        };
        /** @description The whole evidence ledger in one payload (cockpit + grader read this). */
        StudyDetail: {
            study: components["schemas"]["Study"];
            dataset_version?: components["schemas"]["DatasetVersion"];
            hypotheses?: components["schemas"]["Hypothesis"][];
            runs?: components["schemas"]["Run"][];
            critiques?: components["schemas"]["Critique"][];
            decisions?: components["schemas"]["Decision"][];
            feedback?: components["schemas"]["Feedback"][];
            artifacts?: components["schemas"]["Artifact"][];
            /** @description Current agent recommendation rendered in the cockpit. */
            recommendation?: string;
        };
        GradeResult: {
            study_id: string;
            rubric_name?: string;
            rubric_version?: number;
            /** @enum {string} */
            verdict: "done" | "not_done";
            passed_required?: number;
            total_required?: number;
            checks: {
                id: string;
                category?: string;
                required: boolean;
                passed: boolean;
                detail?: string;
            }[];
        };
    };
    responses: {
        /** @description Malformed request body. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid internal token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example study_01HZX */
        StudyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStudies: {
        parameters: {
            query?: {
                status?: "open" | "done" | "stopped";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of studies. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        studies: components["schemas"]["Study"][];
                    };
                };
            };
        };
    };
    createStudy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudyRequest"];
            };
        };
        responses: {
            /** @description Study created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateStudyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getStudy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The study and its complete ledger. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamStudy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream of live agent activity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    suggestChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example study_01HZX */
                studyId: components["parameters"]["StudyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The human's natural-language steering message. */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Message queued for injection into the session. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description The session is not ready yet (no live session to inject into). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The agent runtime is not configured or unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    profileDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                };
            };
        };
        responses: {
            /** @description Dataset profiled; data contract written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    proposeExperiments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                    /** @description Agent-authored hypothesis cards to persist (the agent reasons in hypotheses; the human approves them). When present these are persisted and their ids returned; when absent, N seeded library cards are returned instead. */
                    hypotheses?: {
                        statement: string;
                        rationale?: string;
                        model_family?: string;
                        features?: string[];
                        expected_outcome?: string;
                    }[];
                    /**
                     * @description Number of library cards to return when `hypotheses` is omitted.
                     * @default 6
                     */
                    n?: number;
                };
            };
        };
        responses: {
            /** @description Proposed hypotheses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        hypotheses: components["schemas"]["Hypothesis"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    requestApproval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Pending approval created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        approval_id: string;
                        /** @enum {string} */
                        status: "pending";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    launchExperiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    manifest: components["schemas"]["ExperimentManifest"];
                    /** @description The approval authorizing this compute. */
                    approval_id?: string;
                };
            };
        };
        responses: {
            /** @description Run created (may still be running). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No approval on file, or budget exceeded. */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Manifest invalid (e.g. banned column in features, tune_on=test). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The Modal runner is unreachable or MODAL_RUNNER_URL is not configured. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    queryRuns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunQuery"];
            };
        };
        responses: {
            /** @description Matching runs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: components["schemas"]["Run"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    recordCritique: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                    target_run_id?: string;
                    /** @enum {string} */
                    kind: "leakage" | "test_set_tuning" | "metric" | "calibration" | "robustness";
                    finding: string;
                    recommendation?: string;
                    /** @enum {string} */
                    led_to_decision?: "promote" | "reject" | "rerun" | "branch" | "stop";
                };
            };
        };
        responses: {
            /** @description Critique recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Critique"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    recordDecision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                    /** @enum {string} */
                    action: "promote" | "reject" | "rerun" | "branch" | "stop";
                    promoted_run_id?: string;
                    rejected_run_id?: string;
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Decision recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Decision"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    recordHumanFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Feedback"];
            };
        };
        responses: {
            /** @description Feedback recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    writeReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                    /**
                     * @default model_card
                     * @enum {string}
                     */
                    report_type?: "model_card" | "summary";
                };
            };
        };
        responses: {
            /** @description Report generated and stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    gradeStudy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    study_id: string;
                };
            };
        };
        responses: {
            /** @description Grading result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
